// Page content for index (portfolio) page
const indexContent = {
    title: "Best Affordable Home Staging in Los Angeles and Pasadena",
    content: `
        <!-- SEO Content Container -->
        <section class="seo-content-container visually-hidden">
            <h2>Fast, Affordable Home Staging Services</h2>
            <p>Oliva Home Staging provides the best, most affordable home staging services in Los Angeles and Pasadena. Our fast, professional staging transforms your property with a flat investment that includes 3 months of service, complete design, staging, and move-out. We offer some of the best rates without compromising quality.</p>
            <p>Serving Los Angeles, Pasadena, and surrounding areas with fast turnaround times and affordable pricing.</p>
        </section>
        
        <!-- Service Equation Container -->
        <section class="equation-container" role="main" aria-label="Home Staging Service Package">
            <!-- Investment Item - Pig Icon -->
            <div class="equation-item">
                <img src="equation_graphic_icons/pig-icon.svg" alt="Affordable Home Staging Flat Rate Investment" class="equation-icon">
                <div class="equation-text">
                  <div class="equation-number">1</div>  
                  <div class="equation-title">Flat</div>
                    <div class="equation-title">Investment</div>
                </div>
            </div>
            
            <div class="equation-operator">=</div>
            
            <!-- Duration Item - Calendar Icon -->
            <div class="equation-item">
                <img src="equation_graphic_icons/calendar-icon.svg" alt="3 Months Home Staging Service Included" class="equation-icon">
                <div class="equation-text">
                    <div class="equation-number">3</div>
                    <div class="equation-title">Months</div>
                    <div class="equation-title">Included</div>
                </div>
            </div>
            
            <div class="equation-operator">+</div>
            
            <!-- Design Item - Plan Icon -->
            <div class="equation-item">
                <img src="equation_graphic_icons/plan-icon.svg" alt="Professional Home Staging Design Los Angeles" class="equation-icon">
                <div class="equation-text">
                    <div class="equation-title">Design</div>
                </div>
            </div>
            
            <div class="equation-operator">+</div>
            
            <!-- Staging Item - Bedroom Icon -->
            <div class="equation-item">
                <img src="equation_graphic_icons/bedroom-icon.svg" alt="Fast Home Staging Setup Pasadena" class="equation-icon">
                <div class="equation-text">
                    <div class="equation-title">Stage</div>
                </div>
            </div>
            
            <div class="equation-operator">+</div>
            
            <!-- Move Out Item - Truck Icon -->
            <div class="equation-item">
                <img src="equation_graphic_icons/truck-icon.svg" alt="Home Staging Move Out Service" class="equation-icon">
                <div class="equation-text">
                    <div class="equation-title">Move out</div>
                </div>
            </div>
        </section>
        
        <!-- Photo Showcase Container -->
        <section id="portfolio" class="carousel-container-section" role="complementary" aria-label="Home Staging Portfolio">
            <h2 class="showcase-title">Portfolio</h2>
            <div class="carousel-container">
                <button class="carousel-btn carousel-btn-prev" aria-label="Previous photo" onclick="changePhoto(-1)">‹</button>
                <div class="carousel-wrapper">
                    <div class="carousel-track" id="carouselTrack">
                        <!-- Carousel slides will be dynamically generated by JavaScript -->
                    </div>
                </div>
                <button class="carousel-btn carousel-btn-next" aria-label="Next photo" onclick="changePhoto(1)">›</button>
            </div>
            <!-- Carousel Navigation Indicators -->
            <div class="carousel-indicators" id="carouselIndicators">
                <!-- Indicators will be dynamically generated by JavaScript -->
            </div>
        </section>
    `
};